- name: Deployment configuration trans
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yml"
    dest: $HOME

- name: Deploy configure
  shell: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yml"
  args:
    chdir: $HOME
