Description: >
  CAPSTONE - HuyAQ
  AWS EKS Cluster infrastructure

Parameters:
  EnvironmentName:
    Description: Prefixed Env resource names
    Type: String

Resources:
  EKSRoles:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-Roles
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  ClusterProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${EnvironmentName}-ClusterProfile
      Path: "/"
      Roles:
        - !Ref EKSRoles

  CapstoneCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.19"
      Name: !Sub ${EnvironmentName}-Cluster
      RoleArn: !GetAtt EKSRoles.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub ${EnvironmentName}-SecurityGR
        SubnetIds: 
          Fn::Split:
            - ","
            - Fn::ImportValue: !Sub ${EnvironmentName}-PUB-NETS

Outputs:
  EksID:
    Description: EKS Identify
    Value: !Ref CapstoneCluster
    Export:
      Name: !Sub ${EnvironmentName}-EKSCluster

  EKSRoleArn:
    Description: AWS resources accessibility and create
    Value: !GetAtt EKSRoles.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKSRoles