Description: >
  CAPSTONE - HuyAQ
  AWS EKS Cluster Direction infrastructure

Parameters:
  EnvironmentName:
    Description: Prefixed Env resource names
    Type: String
  SSHKey:
    Description: SSH key
    Type: String
  AMI:
    Description: Application and OS Images
    Type: String

Resources:
  SecurityGrInstance:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-SecurityGRDirection
      GroupDescription: Direction allow ports
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  DirectionServe:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups: 
        - Ref: SecurityGrInstance
      KeyName: !Ref SSHKey
      ImageId: !Ref AMI
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-directionServe
        - Key: Project
          Value: !Ref EnvironmentName