- name: "PyApp Deployment"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ANSIBLE_HOST_KEY_CHECKING: False
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  roles:
    - kubernetes
  tasks:
    - name: Update latest image deployment
      shell: "./bin/kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}-app=dockertonymd/{{ ENVIRONMENT_NAME }}:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: Deploy successful status
      shell: "./bin/kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME
